Repository GSM-MSG/Hi-v2-FrontEnd, pull requests merged in 2023-10, with the labels that each got.

#59 🔀 학생 예약 상태 변경 모달 추가 퍼블리싱 및 기능 구현
  atoms/atom.ts
  components/UserPage/StuState/index.tsx
  components/UserPage/StuState/style.ts
  components/UserPage/UserItem/index.tsx
  components/UserPage/UserItemList/index.tsx
  types/UserItemListType.ts
  types/UserItemType.ts
  types/components/UserListType.ts
Labels: ♻️ Refactor, ✨ Feature, 🎨 Publishing

#61 :lipstick: Add my page menu
  components/Header/index.tsx
  components/Header/style.ts
  types/style/Header.ts
Labels: 3️⃣ Priority: Low, 🎨 Publishing

#62 🔀 예약 모달 검색 기능 수정 및 스타일 수정
  components/ReservationPage/ReservationModal/Page/Completed/style.ts
  components/ReservationPage/ReservationModal/Page/MemberSelect/index.tsx
  components/ReservationPage/ReservationModal/Page/MemberSelect/style.ts
  components/ReservationPage/ReservationModal/Page/PlaceSelect/index.tsx
  components/ReservationPage/ReservationModal/Page/Reason/index.tsx
  components/ReservationPage/ReservationModal/style.ts
Labels: 3️⃣ Priority: Low, ⚡️performance, 🎨 Publishing

#64 🔀 학생 예약 상태 변경 모달 파일 위치 변경
  components/UserPage/StuStateModal/index.tsx
  components/UserPage/StuStateModal/style.ts
  components/UserPage/UserItem/index.tsx
  components/UserPage/UserItemList/index.tsx
Labels: 1️⃣ Priority: High, 🐞 Bug

#65 🔀 유저 검색 기능 추가
  atoms/atom.ts
  components/Common/Input/index.tsx
  components/UserPage/index.tsx
  components/UserPage/style.ts
Labels: 1️⃣ Priority: High, ✨ Feature

#66 🔀 윈도우, 맥 home style 수정
  components/HomePage/style.ts
Labels: 3️⃣ Priority: Low, ⚡️ Simple, 🎨 Publishing

#67 🔀 유저 검색 input 스타일 수정
  components/UserPage/style.ts
Labels: 3️⃣ Priority: Low, 🎨 Publishing

#68 🔀 예약 모달 위치 style 수정
  components/Login/style.ts
  components/Portal/style.ts
  components/ReservationPage/ReservationModal/style.ts
Labels: 3️⃣ Priority: Low, ⚡️ Simple, 🎨 Publishing

#69 🔀 예약 모달 Input 컴포넌트 적용, 버튼 예약 상태에 따라 style 변경
  components/Common/Input/index.tsx
  components/Common/Input/style.ts
  components/ReservationPage/ReservationModal/Page/MemberSelect/index.tsx
  components/ReservationPage/ReservationModal/Page/MemberSelect/style.ts
  components/ReservationPage/ReservationModal/index.tsx
  components/UserPage/index.tsx
  components/common/Button/index.tsx
  components/common/Button/style.ts
  package-lock.json
  types/components/ButtonPropsType.ts
  types/components/InputPropsType.ts
  yarn.lock
Labels: 3️⃣ Priority: Low, ⚡️ Simple, 🎨 Publishing

#70 🔀 Hi의 모달 관리 코드를 리팩토링 했습니다.
  atoms/atom.ts
  components/Header/index.tsx
  components/ReservationPage/index.tsx
  components/UserPage/UserItem/index.tsx
  components/UserPage/UserItemList/index.tsx
  hooks/useModal.tsx
  layout/index.tsx
  modals/LoginModal/index.tsx
  modals/LoginModal/style.ts
  modals/ReservationModal/Page/Completed/index.tsx
  modals/ReservationModal/Page/Completed/style.ts
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/MemberSelect/style.ts
  modals/ReservationModal/Page/PlaceSelect/index.tsx
  modals/ReservationModal/Page/PlaceSelect/style.ts
  modals/ReservationModal/Page/Reason/index.tsx
  modals/ReservationModal/Page/Reason/style.ts
  modals/ReservationModal/index.tsx
  modals/ReservationModal/style.ts
  modals/StuStateModal/index.tsx
  modals/StuStateModal/style.ts
  types/UserItemType.ts
Labels: 3️⃣ Priority: Low, ♻️ Refactor, ⚡️performance

#71 🔀 유저 권한 정보 표시 기능 추가
  components/UserPage/UserItem/index.tsx
  components/UserPage/UserItem/style.ts
  types/UserItemType.ts
Labels: 2️⃣ Priority: Medium, ✨ Feature, 🎨 Publishing

#72 🔀 공지 글 작성, 수정, 삭제 권한 설정
  components/NoticePage/NoticeDetail/index.tsx
  components/NoticePage/NoticeItem/index.tsx
  components/NoticePage/index.tsx
Labels: ♻️ Refactor, ✨ Feature

#73 🔀 Button, Input 컴포넌트 Props 타입 상속
  components/Common/Input/index.tsx
  components/common/Button/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
  types/components/ButtonPropsType.ts
  types/components/InputPropsType.ts
Labels: 3️⃣ Priority: Low, ⚡️performance

#75 🔀 예약 모달 닫을 시 예약 상태를 지우는 코드 개선
  hooks/useDeleteReservationStatus.tsx
  modals/ReservationModal/Page/Completed/index.tsx
  modals/ReservationModal/index.tsx
Labels: 3️⃣ Priority: Low, ⚡️performance

#76 🔀 마이페이지 퍼블리싱
  components/MyPage/index.tsx
  components/MyPage/style.ts
  pages/my-page.tsx
Labels: 1️⃣ Priority: High, 🎨 Publishing

#77 🔀 마이페이지 기능 구현
  components/MyPage/index.tsx
  components/MyPage/style.ts
  types/MyPageType.ts
Labels: 1️⃣ Priority: High, ✨ Feature

#78 🔀 스크롤에 따라 스타일이 변하는 로직 삭제
  components/Header/index.tsx
  components/Header/style.ts
Labels: 3️⃣ Priority: Low, ⚡️performance

#79 🔀 예약 테이블 퍼블리싱 및 예약 데이터 다루는 기초 로직 작성, 모달 단계 수정
  assets/svg/index.ts
  atoms/atom.ts
  components/ReservationPage/ReservationDetailPage/index.tsx
  components/ReservationPage/ReservationTableItem/index.tsx
  components/ReservationPage/ReservationTableItem/style.ts
  components/ReservationPage/index.tsx
  components/ReservationPage/style.ts
  hooks/useDeleteReservationStatus.tsx
  hooks/useFetch.tsx
  lib/ToastOptions.ts
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/PlaceSelect/index.tsx
  modals/ReservationModal/Page/PlaceSelect/style.ts
  modals/ReservationModal/Page/Reason/index.tsx
  modals/ReservationModal/index.tsx
  pages/_app.tsx
  pages/reservation/detail/index.tsx
  types/modals/ReservationData.ts
  types/style/Header.ts
Labels: 2️⃣ Priority: Medium, ⚡️performance, ✨ Feature, 🎨 Publishing

#80 🔀 스크롤 관련 HeaderProps 삭제
  assets/svg/CancelXMark.tsx
  assets/svg/SmallXMark.tsx
  assets/svg/XMark.tsx
  assets/svg/index.ts
  components/Header/index.tsx
  components/ReservationPage/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
Labels: 3️⃣ Priority: Low, ⚡️ Simple

#81 🔀 Update url 마킹 및 input style 수정
  components/Common/Input/index.tsx
  components/Common/Input/style.ts
  components/NoticePage/NoticeDetail/index.tsx
  components/UserPage/index.tsx
  types/components/InputPropsType.ts
Labels: 3️⃣ Priority: Low, ♻️ Refactor

#83 🔀 GET 요청 로직 간소화
  components/MyPage/index.tsx
  components/NoticePage/NoticeDetail/index.tsx
  components/NoticePage/NoticeItem/index.tsx
  components/NoticePage/NoticeItemList/index.tsx
  components/NoticePage/index.tsx
  components/ReservationPage/ReservationDetailPage/index.tsx
  components/ReservationPage/ReservationTableItem/index.tsx
  components/ReservationPage/index.tsx
  components/UserPage/UserItemList/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
Labels: 3️⃣ Priority: Low, ♻️ Refactor

#84 🔀 유저 권한 변경 모달 퍼블리싱 및 기능 구현
  components/UserPage/UserItem/index.tsx
  modals/UserRoleChangeModal/index.tsx
  modals/UserRoleChangeModal/style.ts
Labels: 1️⃣ Priority: High, ✨ Feature, 🎨 Publishing

#86 🔀 권한 수정 모달 버튼 UI 수정
  assets/svg/SelectedCheck.tsx
  assets/svg/index.ts
  modals/UserRoleChangeModal/index.tsx
  modals/UserRoleChangeModal/style.ts
Labels: 🎨 Publishing

#87 🔀 예약 테이블 가져오는 기능 업데이트
  atoms/atom.ts
  components/Common/Modal/Title.ts
  components/ReservationPage/ReservationDetailPage/index.tsx
  components/ReservationPage/ReservationTableItem/index.tsx
  components/ReservationPage/ReservationTableItem/style.ts
  components/ReservationPage/index.tsx
  components/ReservationPage/style.ts
  modals/ReservationModal/Page/Completed/index.tsx
  modals/ReservationModal/Page/Reason/index.tsx
  modals/ReservationModal/PlaceSelect/index.tsx
  modals/ReservationModal/PlaceSelect/style.ts
  types/modals/ReservationData.ts
  yarn.lock
Labels: 1️⃣ Priority: High, ⚡️performance, 🎨 Publishing

#88 🔀 예약 관련 기능 구현 및 예약 관련 모달 퍼블리싱
  assets/svg/RepresentativeIcon.tsx
  assets/svg/TableCheckIcon.tsx
  assets/svg/index.ts
  components/Common/Modal/Title.ts
  components/ReservationPage/ReservationTableItem/index.tsx
  components/ReservationPage/index.tsx
  modals/DeleteTableCheckModal/index.tsx
  modals/DeleteTableCheckModal/style.ts
  modals/LeaveReservationTableModal/index.tsx
  modals/LeaveReservationTableModal/style.ts
  modals/PlaceSelect/index.tsx
  modals/PlaceSelect/style.ts
  modals/RepresentativeMandateModal/index.tsx
  modals/RepresentativeMandateModal/style.ts
  modals/ReservationModal/Page/Completed/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ViewReservationModal/index.tsx
  modals/ViewReservationModal/style.ts
  types/modals/ViewReservationData.ts
Labels: ✨ Feature, 🎨 Publishing

#89 🔀 예약 확인 모달 퍼블리싱 및 명단 검색, 예약 로직 수정
  components/ReservationPage/ReservationTableItem/index.tsx
  modals/RepresentativeMandateModal/index.tsx
  modals/ReservationModal/ConfirmReservationModal/index.tsx
  modals/ReservationModal/ConfirmReservationModal/style.ts
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/Reason/index.tsx
  modals/ViewReservationModal/index.tsx
Labels: ⚡️ Simple, ⚡️performance, 🎨 Publishing

#90 🔀 예약 상세조회, 전체 삭제 버튼 추가
  components/Header/index.tsx
  components/ReservationPage/index.tsx
  components/ReservationPage/style.ts
Labels: ⚡️performance, 🎨 Publishing
