Repository GSM-MSG/Hi-v2-FrontEnd, pull requests merged in 2023-09, with the labels that each got.

#47 🔀 공지 상세 수정 버튼 위치 변겅
  components/NoticePage/NoticeDetail/style.ts
Labels: 🎨 Publishing

#48 🔀 공지페이지 아이템 반응형 및 공지 에러 메시지 수정
  assets/svg/XMark.tsx
  components/NoticePage/NoticeDetail/index.tsx
  components/NoticePage/NoticeDetail/style.ts
  components/NoticePage/NoticeItem/index.tsx
  components/NoticePage/NoticeItem/style.ts
  components/NoticePage/WritePage/index.tsx
  components/NoticePage/index.tsx
  components/NoticePage/style.ts
Labels: 🎨 Publishing

#49 🔀 공지 상세 페이지 스타일 추가
  components/NoticePage/NoticeDetail/style.ts
Labels: 🎨 Publishing

#50 🔀 공지 목록, 작성, 상세 페이지 반응형
  components/Common/PageContainer/style.ts
  components/NoticePage/NoticeDetail/style.ts
  components/NoticePage/NoticeItem/style.ts
  components/NoticePage/WritePage/style.ts
Labels: 🎨 Publishing

#52 🔀 권한 조회
  components/Header/index.tsx
  components/Header/style.ts
  types/components/GetRoleTypes.ts
  types/style/Header.ts
Labels: 3️⃣ Priority: Low, ✨ Feature, 🎨 Publishing

#51 🔀 유저(학생 정보) 페이지 퍼블리싱
  components/UserPage/UserItem/index.tsx
  components/UserPage/UserItem/style.ts
  components/UserPage/UserItemList/index.tsx
  components/UserPage/UserItemList/style.ts
  components/UserPage/index.tsx
  components/UserPage/style.ts
  pages/user.tsx
Labels: 🎨 Publishing

#53 🔀 권한 조회 방식 변경
  components/Header/index.tsx
  components/Header/style.ts
  types/components/GetRoleTypes.ts
  types/style/Header.ts
Labels: 3️⃣ Priority: Low, ⚡️ Simple

#54 🔀 권한 조회 로직 수정
  components/Header/index.tsx
Labels: 3️⃣ Priority: Low, ⚡️performance, 🐞 Bug

#55 🔀 학생 정보 조회 기능 추가
  components/NoticePage/NoticeItemList/index.tsx
  components/UserPage/UserItem/index.tsx
  components/UserPage/UserItem/style.ts
  components/UserPage/UserItemList/index.tsx
  next.config.js
  types/UserItemListType.ts
  types/UserItemType.ts
Labels: 2️⃣ Priority: Medium, ✨ Feature

#56 🔀 예약 상세 모달 구현
  atoms/atom.ts
  components/Common/Modal/Title.ts
  components/Header/index.tsx
  components/HomePage/style.ts
  components/Login/index.tsx
  components/NoticePage/NoticeDetail/style.ts
  components/NoticePage/NoticeItem/style.ts
  components/NoticePage/WritePage/index.tsx
  components/Portal/index.tsx
  components/ReservationPage/ReservationModal/Page/Completed/index.tsx
  components/ReservationPage/ReservationModal/Page/Completed/style.ts
  components/ReservationPage/ReservationModal/Page/MemberSelect/index.tsx
  components/ReservationPage/ReservationModal/Page/MemberSelect/style.ts
  components/ReservationPage/ReservationModal/Page/PlaceSelect/index.tsx
  components/ReservationPage/ReservationModal/Page/PlaceSelect/style.ts
  components/ReservationPage/ReservationModal/Page/Reason/index.tsx
  components/ReservationPage/ReservationModal/Page/Reason/style.ts
  components/ReservationPage/ReservationModal/index.tsx
Labels: 2️⃣ Priority: Medium, ✨ Feature, 🎨 Publishing

#57 🔀 전체 학생 조회 로직 변경
  components/UserPage/UserItem/index.tsx
  components/UserPage/UserItemList/index.tsx
  types/UserItemType.ts
Labels: 2️⃣ Priority: Medium, ♻️ Refactor, ⚡️ Simple

#58 🔀 학생 홈베이스 예약 상태 변경 기능 추가
  components/UserPage/UserItem/index.tsx
  components/UserPage/UserItemList/index.tsx
  types/UserItemType.ts
Labels: 2️⃣ Priority: Medium, ✨ Feature
