Repository GSM-MSG/Hi-v2-FrontEnd, pull requests merged in 2023-11, with the labels that each got.

#91 🔀 유저의 권한을 가져오는 useGetRole hook 구현
  components/Header/index.tsx
  components/MyPage/index.tsx
  components/NoticePage/NoticeDetail/index.tsx
  components/NoticePage/NoticeItem/index.tsx
  components/NoticePage/index.tsx
  components/UserPage/UserItem/index.tsx
  hooks/useGetRole.tsx
Labels: ♻️ Refactor

#92 🔀 유저 권한 api 횟수 줄이기
  components/NoticePage/NoticeItem/index.tsx
  components/NoticePage/NoticeItemList/index.tsx
  components/UserPage/UserItem/index.tsx
  components/UserPage/UserItemList/index.tsx
  hooks/useGetRole.tsx
  types/NoticeItemType.ts
  types/UserItemType.ts
  types/hooks/useGetRole.ts
Labels: ♻️ Refactor

#94 🔀 예약 수정 기능 추가
  components/HomePage/index.tsx
  components/ReservationPage/ReservationTableItem/index.tsx
  components/ReservationPage/ReservationTableItem/style.ts
  components/ReservationPage/index.tsx
  components/ReservationPage/style.ts
  modals/ReservationModal/ConfirmReservationModal/index.tsx
  modals/ReservationModal/Page/Completed/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/MemberSelect/style.ts
  modals/ReservationModal/Page/Reason/index.tsx
  modals/ReservationModal/index.tsx
  types/components/InputPropsType.ts
Labels: ✨ Feature

#97 🔀 기능 소개 박스 리스트 리팩토링
  components/HomePage/FunctionBox.tsx
  components/HomePage/index.tsx
  constants/homeObject.ts
Labels: ♻️ Refactor

#96 🔀 헤더 메뉴 리팩토링
  components/Header/index.tsx
  components/Header/style.ts
  components/constants/headerObject.ts
Labels: ♻️ Refactor

#98 🔀 재예약 오류 해결
  components/MyPage/index.tsx
  components/ReservationPage/ReservationTableItem/index.tsx
  components/ReservationPage/style.ts
  modals/ViewReservationModal/style.ts
  types/UserItemType.ts
Labels: 🐞 Bug

#95 🔀 옵셔널 타입, import 경로 수정
  atoms/atom.ts
  pages/reservation/detail/index.tsx
Labels: 1️⃣ Priority: High, ⚡️ Simple, 🐞 Bug

#99 Revert "🔀 재예약 오류 해결"
  components/Header/index.tsx
  components/Header/style.ts
  components/HomePage/FunctionBox.tsx
  components/HomePage/index.tsx
  components/constants/headerObject.ts
  constants/homeObject.ts
Labels: 0️⃣ Priority: Critical

#102 Deploy
  atoms/atom.ts
  components/Header/index.tsx
  components/Header/style.ts
  components/HomePage/FuntionBox.tsx
  components/HomePage/index.tsx
  components/MyPage/index.tsx
  components/ReservationPage/ReservationTableItem/index.tsx
  components/ReservationPage/style.ts
  components/constants/headerObject.ts
  constants/homeObject.ts
  modals/ViewReservationModal/style.ts
  pages/reservation/detail/index.tsx
  types/UserItemType.ts
Labels: 🌏 Deploy

#103 Deploy
  components/Header/index.tsx
  components/Header/style.ts
  components/HomePage/FunctionBox.tsx
  components/HomePage/index.tsx
  components/ReservationPage/ReservationTableItem/index.tsx
  constants/headerObject.ts
  constants/homeObject.ts
Labels: 🌏 Deploy

#104 🔀 로그아웃 api 연결 및 기능 구현
  components/Header/index.tsx
  hooks/useLogout.tsx
Labels: 2️⃣ Priority: Medium, ✨ Feature

#105 🔀 유저 프로필 이미지 비율 설정
  assets/svg/UserProfile.tsx
  components/MyPage/index.tsx
  components/MyPage/style.ts
  components/UserPage/UserItem/index.tsx
  components/UserPage/UserItem/style.ts
Labels: 3️⃣ Priority: Low, 🐞 Bug, 🎨 Publishing

#106 🔀 build 오류 해결
  components/MyPage/index.tsx
  components/UserPage/UserItemList/index.tsx
Labels: ⚡️ Simple, 🐞 Bug

#107 Deploy
  assets/svg/UserProfile.tsx
  components/Header/index.tsx
  components/MyPage/index.tsx
  components/MyPage/style.ts
  components/UserPage/UserItem/index.tsx
  components/UserPage/UserItem/style.ts
  components/UserPage/UserItemList/index.tsx
  hooks/useLogout.tsx
Labels: 🌏 Deploy

#109 🔀 common 폴더 이름 변경
  components/HomePage/index.tsx
  components/ReservationPage/index.tsx
  components/UserPage/UserItem/index.tsx
  components/commons/Button/index.tsx
  components/commons/Button/style.ts
  components/commons/Input/index.tsx
  components/commons/Input/style.ts
  components/commons/Modal/Title.ts
  components/commons/PageContainer/index.tsx
  components/commons/PageContainer/style.ts
  components/commons/Textarea/index.tsx
  components/commons/Textarea/style.ts
Labels: ⚡️ Simple

#110 🔀 Deploy
  components/HomePage/index.tsx
  components/ReservationPage/index.tsx
  components/UserPage/UserItem/index.tsx
  components/commons/Button/index.tsx
  components/commons/Button/style.ts
  components/commons/Input/index.tsx
  components/commons/Input/style.ts
  components/commons/Modal/Title.ts
  components/commons/PageContainer/index.tsx
  components/commons/PageContainer/style.ts
  components/commons/Textarea/index.tsx
  components/commons/Textarea/style.ts
Labels: 🌏 Deploy

#111 🔀 commons 경로 이름 변경
  components/MyPage/index.tsx
  components/NoticePage/NoticeDetail/index.tsx
  components/NoticePage/WritePage/index.tsx
  components/NoticePage/index.tsx
  components/UserPage/index.tsx
  modals/DeleteTableCheckModal/index.tsx
  modals/LeaveReservationTableModal/index.tsx
  modals/PlaceSelect/index.tsx
  modals/RepresentativeMandateModal/index.tsx
  modals/ReservationModal/ConfirmReservationModal/index.tsx
  modals/ReservationModal/Page/Completed/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/Reason/index.tsx
  modals/StuStateModal/index.tsx
  modals/UserRoleChangeModal/index.tsx
  modals/ViewReservationModal/index.tsx
Labels: ⚡️ Simple

#112 Revert "🔀 commons 경로 이름 변경"
  components/MyPage/index.tsx
  components/NoticePage/NoticeDetail/index.tsx
  components/NoticePage/WritePage/index.tsx
  components/NoticePage/index.tsx
  components/UserPage/index.tsx
  modals/DeleteTableCheckModal/index.tsx
  modals/LeaveReservationTableModal/index.tsx
  modals/PlaceSelect/index.tsx
  modals/RepresentativeMandateModal/index.tsx
  modals/ReservationModal/ConfirmReservationModal/index.tsx
  modals/ReservationModal/Page/Completed/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/Reason/index.tsx
  modals/StuStateModal/index.tsx
  modals/UserRoleChangeModal/index.tsx
  modals/ViewReservationModal/index.tsx
Labels: 0️⃣ Priority: Critical

#113 🔀 common -> commons 경로 변경
  components/MyPage/index.tsx
  components/NoticePage/NoticeDetail/index.tsx
  components/NoticePage/WritePage/index.tsx
  components/NoticePage/index.tsx
  components/UserPage/index.tsx
  modals/DeleteTableCheckModal/index.tsx
  modals/LeaveReservationTableModal/index.tsx
  modals/PlaceSelect/index.tsx
  modals/RepresentativeMandateModal/index.tsx
  modals/ReservationModal/ConfirmReservationModal/index.tsx
  modals/ReservationModal/Page/Completed/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/Reason/index.tsx
  modals/StuStateModal/index.tsx
  modals/UserRoleChangeModal/index.tsx
  modals/ViewReservationModal/index.tsx
Labels: ⚡️ Simple, 🐞 Bug

#115 🔀 master to develop
  components/MyPage/index.tsx
  components/NoticePage/NoticeDetail/index.tsx
  components/NoticePage/WritePage/index.tsx
  components/NoticePage/index.tsx
  components/UserPage/index.tsx
  modals/DeleteTableCheckModal/index.tsx
  modals/LeaveReservationTableModal/index.tsx
  modals/PlaceSelect/index.tsx
  modals/RepresentativeMandateModal/index.tsx
  modals/ReservationModal/ConfirmReservationModal/index.tsx
  modals/ReservationModal/Page/Completed/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/Reason/index.tsx
  modals/StuStateModal/index.tsx
  modals/UserRoleChangeModal/index.tsx
  modals/ViewReservationModal/index.tsx
Labels: 0️⃣ Priority: Critical

#116 🔀 commons 내보내기 수정
  components/HomePage/index.tsx
  components/MyPage/index.tsx
  components/NoticePage/NoticeDetail/index.tsx
  components/NoticePage/WritePage/index.tsx
  components/NoticePage/index.tsx
  components/ReservationPage/index.tsx
  components/UserPage/UserItem/index.tsx
  components/UserPage/index.tsx
  components/commons/index.ts
  modals/DeleteTableCheckModal/index.tsx
  modals/LeaveReservationTableModal/index.tsx
  modals/PlaceSelect/index.tsx
  modals/RepresentativeMandateModal/index.tsx
  modals/ReservationModal/ConfirmReservationModal/index.tsx
  modals/ReservationModal/Page/Completed/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/Reason/index.tsx
  modals/StuStateModal/index.tsx
  modals/UserRoleChangeModal/index.tsx
  modals/ViewReservationModal/index.tsx
Labels: ⚡️performance

#117 🔀 Deploy
  components/HomePage/index.tsx
  components/MyPage/index.tsx
  components/NoticePage/NoticeDetail/index.tsx
  components/NoticePage/WritePage/index.tsx
  components/NoticePage/index.tsx
  components/ReservationPage/index.tsx
  components/UserPage/UserItem/index.tsx
  components/UserPage/index.tsx
  components/commons/index.ts
  modals/DeleteTableCheckModal/index.tsx
  modals/LeaveReservationTableModal/index.tsx
  modals/PlaceSelect/index.tsx
  modals/RepresentativeMandateModal/index.tsx
  modals/ReservationModal/ConfirmReservationModal/index.tsx
  modals/ReservationModal/Page/Completed/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/Reason/index.tsx
  modals/StuStateModal/index.tsx
  modals/UserRoleChangeModal/index.tsx
  modals/ViewReservationModal/index.tsx
Labels: 🌏 Deploy

#118 🔀 이미지 오류 해결
  components/MyPage/index.tsx
Labels: ⚡️ Simple, 🐞 Bug

#119 🔀 Deploy
  components/MyPage/index.tsx
Labels: 🌏 Deploy

#108 🔀 토큰 재발급
  apis/TokenManager.ts
  apis/api.ts
  apis/index.ts
  atoms/atom.ts
  components/Header/style.ts
  components/HomePage/FunctionBox.tsx
  components/MyPage/index.tsx
  components/NoticePage/NoticeDetail/index.tsx
  components/NoticePage/NoticeItem/index.tsx
  components/NoticePage/NoticeItemList/index.tsx
  components/NoticePage/WritePage/index.tsx
  components/Portal/index.tsx
  components/ReservationPage/ReservationTableItem/index.tsx
  components/ReservationPage/index.tsx
  components/SEO/index.tsx
  components/UserPage/UserItem/index.tsx
  components/UserPage/UserItemList/index.tsx
  components/UserPage/index.tsx
  components/commons/Button/index.tsx
  components/commons/Button/style.ts
  components/commons/Input/index.tsx
  components/commons/Input/style.ts
  components/commons/PageContainer/index.tsx
  components/commons/PageContainer/style.ts
  components/commons/Textarea/index.tsx
  components/commons/Textarea/style.ts
  hooks/index.ts
  hooks/useDeleteReservationStatus.tsx
  hooks/useFetch.tsx
  hooks/useGetRole.tsx
  hooks/useLogout.tsx
  layout/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/Reason/index.tsx
  modals/StuStateModal/index.tsx
  modals/StuStateModal/style.ts
  modals/UserRoleChangeModal/index.tsx
  modals/ViewReservationModal/index.tsx
  types/LayoutType.ts
  types/apis/StorageTokenNames.ts
  types/apis/TokensType.ts
  types/apis/index.ts
  types/components/FunctionBoxPropsType.ts
  types/components/GetRoleType.ts
  types/components/MyPageType.ts
  types/components/NoticeDetailType.ts
  types/components/NoticeItemListType.ts
  types/components/NoticeItemType.ts
  types/components/NoticeModifyType.ts
  types/components/PortalPropsType.ts
  types/components/SeoPropsType.ts
  types/components/TextAreaPropsType.ts
  types/components/UserItemListType.ts
  types/components/UserItemType.ts
  types/components/index.ts
  types/hooks/index.ts
  types/modals/ReservationData.ts
  types/modals/ViewReservationData.ts
  types/modals/index.ts
  types/style/Header.ts
Labels: ✨ Feature
