Repository GSM-MSG/Hi-v2-FrontEnd, pull requests merged in 2023-08, with the labels that each got.

#4 Hi header 디자인 변경
  assets/svg/HiWhiteLogo.tsx
  assets/svg/index.ts
  components/Header/index.tsx
  components/Header/style.ts
  components/HomePage/style.ts
  public/fonts/woff/Pretendard-Black.woff
  public/fonts/woff/Pretendard-Bold.woff
  public/fonts/woff/Pretendard-ExtraBold.woff
  public/fonts/woff/Pretendard-ExtraLight.woff
  public/fonts/woff/Pretendard-Light.woff
  public/fonts/woff/Pretendard-Medium.woff
  public/fonts/woff/Pretendard-Regular.woff
  public/fonts/woff/Pretendard-SemiBold.woff
  public/fonts/woff/Pretendard-Thin.woff
  public/fonts/woff2/Pretendard-Black.woff2
  public/fonts/woff2/Pretendard-Bold.woff2
  public/fonts/woff2/Pretendard-ExtraBold.woff2
  public/fonts/woff2/Pretendard-ExtraLight.woff2
  public/fonts/woff2/Pretendard-Light.woff2
  public/fonts/woff2/Pretendard-Medium.woff2
  public/fonts/woff2/Pretendard-Regular.woff2
  public/fonts/woff2/Pretendard-SemiBold.woff2
  public/fonts/woff2/Pretendard-Thin.woff2
  styles/globals.css
Labels: 3️⃣ Priority: Low, ⚡️ Simple, ⚡️performance

#5 메인페이지 디자인 변경
  assets/svg/ArrowIcon.tsx
  assets/svg/ScrollMouseIcon.tsx
  assets/svg/index.ts
  components/Header/style.ts
  components/HomePage/index.tsx
  components/HomePage/style.ts
  tsconfig.json
Labels: 3️⃣ Priority: Low, ⚡️ Simple

#6 Login 버튼 hover event 추가
  components/Header/style.ts
Labels: 3️⃣ Priority: Low, ⚡️ Simple

#8 update width and padding
  components/Header/index.tsx
  components/Header/style.ts
  components/HomePage/style.ts
  styles/globals.css
Labels: 3️⃣ Priority: Low, ⚡️ Simple

#9 로그인 했을 때 로그인 버튼 로그아웃으로 바꾸기
  assets/svg/HiLogo.tsx
  components/Header/index.tsx
  components/Header/style.ts
  components/HomePage/FuntionBox.tsx
  components/HomePage/style.ts
  package.json
  types/components/FunctionBox.ts
  types/style/Header.ts
  yarn.lock
Labels: 3️⃣ Priority: Low, ⚡️ Simple, ⚡️performance

#10 공지 페이지 퍼블리싱
  components/Header/style.ts
  components/NoticeItem/index.tsx
  components/NoticeItem/style.ts
  components/NoticeItemList/index.tsx
  components/NoticeItemList/style.ts
  components/NoticePage/index.tsx
  components/NoticePage/style.ts
  pages/api/hello.ts
  pages/notice.tsx
  types/NoticeItemType.ts
Labels: 2️⃣ Priority: Medium, 🎨 Publishing

#11 로그인 모달 스타일 수정 및 로그아웃 기능 개발
  atoms/atom.ts
  components/Header/index.tsx
  components/Login/index.tsx
  components/Login/style.ts
  layout/index.tsx
  pages/_app.tsx
  types/LayoutType.ts
Labels: 2️⃣ Priority: Medium, ✨ Feature, 🎨 Publishing

#12 버튼 컴포넌트화
  components/HomePage/index.tsx
  components/HomePage/style.ts
  components/common/Button/index.tsx
  components/common/Button/style.ts
  types/components/ButtonType.ts
Labels: 3️⃣ Priority: Low, ⚡️ Simple, ⚡️performance, 🎨 Publishing

#13 update button props hover
  components/common/Button/index.tsx
  components/common/Button/style.ts
  types/components/ButtonType.ts
Labels: 3️⃣ Priority: Low, ⚡️ Simple

#14 예약페이지 모달 퍼블리싱
  assets/svg/SearchIcon.tsx
  assets/svg/SmallXMark.tsx
  assets/svg/UserPfofile.tsx
  assets/svg/index.ts
  atoms/atom.ts
  components/Common/Modal/Button.ts
  components/Common/Modal/Title.ts
  components/Common/Textarea.ts
  components/Header/index.tsx
  components/Header/style.ts
  components/Login/index.tsx
  components/Login/style.ts
  components/Portal/index.tsx
  components/Portal/style.ts
  components/ReservationPage/ReservationModal/Page/MemberSelection/index.tsx
  components/ReservationPage/ReservationModal/Page/MemberSelection/style.ts
  components/ReservationPage/ReservationModal/Page/Reason/index.tsx
  components/ReservationPage/ReservationModal/Page/Reason/style.ts
  components/ReservationPage/ReservationModal/index.tsx
  components/ReservationPage/ReservationModal/style.ts
  components/ReservationPage/index.tsx
  components/ReservationPage/style.ts
  package.json
  pages/_document.tsx
  pages/reservation.tsx
  types/components/Portal.ts
  yarn.lock
Labels: 2️⃣ Priority: Medium, ✨ Feature, 🎨 Publishing

#15 수정된 예약페이지 모달 퍼블리싱
  components/Common/Modal/Button.ts
  components/Common/Modal/Title.ts
  components/HomePage/index.tsx
  components/Login/style.ts
  components/ReservationPage/ReservationModal/Page/MemberSelection/index.tsx
  components/ReservationPage/ReservationModal/Page/MemberSelection/style.ts
  components/ReservationPage/ReservationModal/Page/Reason/index.tsx
  components/ReservationPage/ReservationModal/Page/Reason/style.ts
  pages/reservation.tsx
Labels: 3️⃣ Priority: Low, ⚡️ Simple, 🎨 Publishing

#17 hasLogin state 을 통한 로그인 상태 관리
  atoms/atom.ts
  components/Header/index.tsx
  utils/Storage.ts
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, 🐞 Bug

#19 공지 작성 페이지 퍼블리싱
  assets/svg/AddImgIcon.tsx
  assets/svg/index.ts
  components/NoticePage/WritePage/index.tsx
  components/NoticePage/WritePage/style.ts
  pages/notice/write.tsx
Labels: 2️⃣ Priority: Medium, 🎨 Publishing

#20 로그인 스타일, recoil import 구문 수정, 백엔드에 accessToken 전달
  apis/api.ts
  components/Login/style.ts
  layout/index.tsx
Labels: 1️⃣ Priority: High, ♻️ Refactor, 🎨 Publishing

#22 타입 작성법 통일
  apis/api.ts
  atoms/atom.ts
  components/Common/Modal/Title.ts
  components/Common/Textarea.ts
  components/HomePage/index.tsx
  components/HomePage/style.ts
  components/ReservationPage/ReservationModal/Page/MemberSelection/index.tsx
  components/ReservationPage/ReservationModal/Page/MemberSelection/style.ts
  components/ReservationPage/ReservationModal/Page/Reason/index.tsx
  components/ReservationPage/ReservationModal/Page/Reason/style.ts
  components/ReservationPage/ReservationModal/index.tsx
  components/ReservationPage/ReservationModal/style.ts
  components/ReservationPage/index.tsx
  components/ReservationPage/style.ts
  hooks/useFetch.tsx
  lib/ToastOptions.ts
  package.json
  pages/_app.tsx
  pages/reservation.tsx
  types/LayoutType.ts
  types/NoticeItemType.ts
  types/components/ButtonPropsType.ts
  types/components/InputPropsType.ts
  types/components/PageContainerPropsType.ts
  types/components/TextAreaProps.ts
  types/components/UserListType.ts
  types/hooks/useFetch.ts
  yarn.lock
Labels: 3️⃣ Priority: Low, ⚡️ Simple, ⚡️performance

#23 버튼 컴포넌트 props 오타 수정
  components/common/Button/index.tsx
Labels: 3️⃣ Priority: Low, ⚡️ Simple

#26 🔀 head title 설정 및 폴더 구조 정리
  components/Common/Textarea.ts
  components/HomePage/index.tsx
  components/NoticePage/index.tsx
  components/ReservationPage/ReservationModal/Page/MemberSelection/index.tsx
  components/ReservationPage/ReservationModal/Page/Reason/index.tsx
  components/SEO/index.tsx
  pages/index.tsx
  pages/notice/index.tsx
  pages/notice/write.tsx
  pages/reservation.tsx
  types/SeoPropsType.ts
Labels: 3️⃣ Priority: Low, ⚡️performance

#27 🔀 공지 작성 페이지 퍼블리싱 수정
  components/NoticePage/WritePage/index.tsx
  components/NoticePage/WritePage/style.ts
Labels: 2️⃣ Priority: Medium, 🎨 Publishing

#29 🔀 공지 상세 페이지 퍼블리싱
  assets/svg/BackArrowIcon.tsx
  assets/svg/index.ts
  components/NoticePage/NoticeDetailPage/index.tsx
  components/NoticePage/NoticeDetailPage/style.ts
  components/NoticePage/NoticeItem/index.tsx
  components/NoticePage/WritePage/style.ts
  pages/notice/detail.tsx
  styles/globals.css
Labels: 2️⃣ Priority: Medium, 🎨 Publishing

#30 🔀 홈페이지 비율 수정
  assets/svg/HiLogo.tsx
  assets/svg/HiWhiteLogo.tsx
  components/Header/style.ts
  components/HomePage/FuntionBox.tsx
  components/HomePage/style.ts
  components/ReservationPage/ReservationModal/Page/MemberSelection/index.tsx
Labels: 3️⃣ Priority: Low, ⚡️ Simple, 🎨 Publishing

#31 홈 그라데이션 적용
  components/Header/style.ts
  components/HomePage/style.ts
Labels: 3️⃣ Priority: Low, ⚡️ Simple, 🎨 Publishing

#32 🔀 공지 작성 기능 구현
  components/Common/Input/index.tsx
  components/Common/Textarea/index.tsx
  components/NoticePage/WritePage/index.tsx
  types/components/InputPropsType.ts
  types/components/TextAreaProps.ts
Labels: 1️⃣ Priority: High, ✨ Feature

#34 🔀 검색 input 구조 변경
  atoms/atom.ts
  components/Common/Textarea/index.tsx
  components/ReservationPage/ReservationModal/Page/Completed/index.tsx
  components/ReservationPage/ReservationModal/Page/MemberSelection/index.tsx
  components/ReservationPage/ReservationModal/Page/MemberSelection/style.ts
  components/ReservationPage/ReservationModal/Page/Reason/index.tsx
  hooks/useFetch.tsx
  types/components/TextAreaProps.ts
Labels: 3️⃣ Priority: Low, ⚡️ Simple, 🎨 Publishing

#35 🔀 홈베이스 예약 기능 추가
  components/Common/Textarea/index.tsx
  components/ReservationPage/ReservationModal/Page/Reason/index.tsx
  types/components/TextAreaProps.ts
Labels: 2️⃣ Priority: Medium, ⚡️performance, ✨ Feature

#37 🔀 page container padding 수정
  components/Common/PageContainer/style.ts
Labels: 3️⃣ Priority: Low, 🎨 Publishing

#38 🔀 예약 페이지에 PageContainer 컴포넌트 적용
  components/ReservationPage/index.tsx
  components/ReservationPage/style.ts
Labels: 3️⃣ Priority: Low, ⚡️ Simple, 🎨 Publishing

#39 예약 현황 페이지 퍼블리싱
  assets/svg/CancelXMark.tsx
  atoms/atom.ts
  components/Header/index.tsx
  components/ReservationPage/ReservationDetailPage/index.tsx
  components/ReservationPage/ReservationModal/Page/MemberSelection/index.tsx
  components/ReservationPage/ReservationModal/Page/MemberSelection/style.ts
  components/ReservationPage/ReservationModal/Page/Reason/index.tsx
  components/ReservationPage/index.tsx
  components/ReservationPage/style.ts
  pages/reservation/detail/[homebaseId].tsx
  pages/reservation/index.tsx
Labels: 3️⃣ Priority: Low, 🎨 Publishing

#40 🔀 interceptor를 이용한 accessToken header에 담기
  apis/api.ts
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#41 🔀 공지 삭제 이후 공지 목록 불러올 때 비동기처리
  components/NoticePage/NoticeItem/index.tsx
Labels: 1️⃣ Priority: High, ♻️ Refactor

#42 🔀 공지글 등록 후 공지 페이지로 이동
  components/NoticePage/WritePage/index.tsx
Labels: ⚡️performance

#43 🔀 공지페이지 index 번호 추가, 글 삭제 toast 설정
  components/NoticePage/NoticeItem/index.tsx
  components/NoticePage/NoticeItem/style.ts
  components/NoticePage/NoticeItemList/index.tsx
  types/NoticeItemListType.ts
  types/NoticeItemType.ts
Labels: 3️⃣ Priority: Low, ⚡️ Simple, ⚡️performance

#44 🔀 공지 상세페이지 기능 구현
  components/NoticePage/NoticeDetail/index.tsx
  components/NoticePage/NoticeDetail/style.ts
  components/NoticePage/NoticeDetailPage/index.tsx
  components/NoticePage/NoticeItem/index.tsx
  pages/notice/[id].tsx
  types/NoticeDetailType.ts
Labels: ♻️ Refactor, ✨ Feature

#45 🔀 공지 수정 버튼 및 기능 추가
  components/NoticePage/NoticeDetail/index.tsx
  components/NoticePage/NoticeDetail/style.ts
  components/NoticePage/NoticeItemList/index.tsx
  components/NoticePage/WritePage/index.tsx
  components/ReservationPage/ReservationDetailPage/index.tsx
  types/NoticeModifyType.ts
Labels: 3️⃣ Priority: Low, ♻️ Refactor, ✨ Feature, 🎨 Publishing
