Repository GSM-MSG/Hi-v2-FrontEnd, pull requests merged in 2024-04, with the labels that each got.

#213 🔀 예약 조회 모달 liine-height 조절
  components/ReservationPage/ReservationTableItem/index.tsx
  modals/ViewReservationModal/ViewReservationData/style.ts
  modals/ViewReservationModal/index.tsx
Labels: 🎨 Publishing

#212 🔀 이미지 최적화
  next.config.js
  package.json
  yarn.lock
Labels: ⚡️performance

#214 Feature/reservation
  modals/DeleteTableCheckModal/index.tsx
  modals/LeaveReservationTableModal/index.tsx
  modals/ReservationModal/Page/Reason/index.tsx
Labels: ⚡️performance, 🎨 Publishing

#215 🔀 Deploy
  components/ReservationPage/ReservationTableItem/index.tsx
  modals/DeleteTableCheckModal/index.tsx
  modals/LeaveReservationTableModal/index.tsx
  modals/ReservationModal/Page/Reason/index.tsx
  modals/ViewReservationModal/ViewReservationData/style.ts
  modals/ViewReservationModal/index.tsx
  next.config.js
  package.json
  yarn.lock
Labels: 🌏 Deploy

#216 🔀 상세조회 모달 7교시 추가
  components/ReservationPage/index.tsx
  modals/PlaceSelectModal/index.tsx
  modals/PlaceSelectModal/style.ts
  modals/ViewReservationModal/style.ts
  modals/index.ts
Labels: ⚡️performance, 🎨 Publishing

#217 🔀 프로젝트 function 컨벤션 통일
  assets/svg/ArrowIcon.tsx
  assets/svg/GAuthLogo.tsx
  assets/svg/HiLoginLogo.tsx
  assets/svg/HiLogo.tsx
  assets/svg/HiWhiteLogo.tsx
  assets/svg/ScrollMouseIcon.tsx
  assets/svg/SearchIcon.tsx
  assets/svg/UserProfile.tsx
  components/Footer/index.tsx
  components/Header/index.tsx
  components/HomePage/Section1/index.tsx
  components/HomePage/Section2/index.tsx
  components/HomePage/Section3/index.tsx
  components/HomePage/index.tsx
  components/NoticePage/Page/index.tsx
  components/Portal/index.tsx
  components/ReservationItem/index.tsx
  components/ReservationPage/index.tsx
  components/SEO/index.tsx
  components/commons/PageContainer/index.tsx
  modals/PlaceSelectModal/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/Reason/index.tsx
  modals/ReservationModal/index.tsx
  pages/reservation.tsx
Labels: ♻️ Refactor

#218 🔀 LCP 향상
  components/Footer/index.tsx
  components/MyPage/index.tsx
  pages/user.tsx
  yarn.lock
Labels: ⚡️performance

#220 Deploy
  assets/svg/ArrowIcon.tsx
  assets/svg/GAuthLogo.tsx
  assets/svg/HiLoginLogo.tsx
  assets/svg/HiLogo.tsx
  assets/svg/HiWhiteLogo.tsx
  assets/svg/ScrollMouseIcon.tsx
  assets/svg/SearchIcon.tsx
  assets/svg/UserProfile.tsx
  components/Footer/index.tsx
  components/Header/index.tsx
  components/HomePage/Section1/index.tsx
  components/HomePage/Section2/index.tsx
  components/HomePage/Section3/index.tsx
  components/HomePage/index.tsx
  components/MyPage/index.tsx
  components/NoticePage/Page/index.tsx
  components/Portal/index.tsx
  components/ReservationItem/index.tsx
  components/ReservationPage/index.tsx
  components/SEO/index.tsx
  components/commons/PageContainer/index.tsx
  modals/PlaceSelectModal/index.tsx
  modals/PlaceSelectModal/style.ts
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/Reason/index.tsx
  modals/ReservationModal/index.tsx
  modals/ViewReservationModal/style.ts
  modals/index.ts
  pages/reservation.tsx
  pages/user.tsx
  yarn.lock
Labels: 🌏 Deploy

#222 🔀 next seo 설정
  assets/png/HiOpenGraphImg.png
  components/SEO/index.tsx
  components/index.ts
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/my-page.tsx
  pages/notice/[id].tsx
  pages/notice/index.tsx
  pages/notice/write.tsx
  pages/reservation.tsx
  pages/user.tsx
  yarn.lock
Labels: ⚙ Setting, ✨ Feature

#223 🔀 Deploy
  assets/png/HiOpenGraphImg.png
  atoms/index.ts
  components/SEO/index.tsx
  components/index.ts
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/my-page.tsx
  pages/notice/[id].tsx
  pages/notice/index.tsx
  pages/notice/write.tsx
  pages/reservation.tsx
  pages/user.tsx
  yarn.lock
Labels: 🌏 Deploy

#225 🔀 Deploy
  libs/gauthLoginUri.ts
Labels: 🌏 Deploy

#226 🔀 특정 시간에 맞춰서 기본 교시 변경
  atoms/index.ts
Labels: ✨ Feature

#227 🔀 Deploy
  atoms/index.ts
Labels: 🌏 Deploy

#228 🔀 period return 함수 else 문 수정
  atoms/index.ts
Labels: ⚡️ Simple
