Repository GSM-MSG/Hi-v2-FrontEnd, pull requests merged in 2024-03, with the labels that each got.

#133 🔀 react-query로 마이그레이션
  apis/queryKeyController.ts
  apis/urlController.ts
  atoms/index.ts
  components/Header/index.tsx
  components/MyPage/index.tsx
  components/NoticePage/NoticeDetail/index.tsx
  components/NoticePage/NoticeItem/index.tsx
  components/NoticePage/NoticeItemList/index.tsx
  components/NoticePage/NoticeWritePage/index.tsx
  components/ReservationPage/ReservationTableItem/index.tsx
  components/ReservationPage/index.tsx
  components/UserPage/UserItem/index.tsx
  components/UserPage/UserItem/style.ts
  components/UserPage/UserItemList/index.tsx
  components/UserPage/UserItemList/style.ts
  components/UserPage/index.tsx
  components/UserPage/style.ts
  hooks/index.ts
  hooks/useFetch.tsx
  hooks/useGetRole.tsx
  modals/DeleteTableCheckModal/index.tsx
  modals/LeaveReservationTableModal/index.tsx
  modals/PlaceSelect/index.tsx
  modals/RepresentativeMandateModal/index.tsx
  modals/ReservationModal/Page/Completed/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/Reason/index.tsx
  modals/ReservationModal/index.tsx
  modals/StuStateModal/index.tsx
  modals/UserRoleChangeModal/index.tsx
  modals/ViewReservationModal/index.tsx
  modals/ViewReservationModal/style.ts
  package.json
  pages/_app.tsx
  types/apis/reservationIdsType.ts
  types/components/NoticeItemType.ts
  types/components/NoticeModifyType.ts
  types/components/NoticeType.ts
  types/components/UserItemListType.ts
  types/components/UserItemType.ts
  types/components/index.ts
  types/hooks/index.ts
  types/hooks/useFetch.ts
  types/hooks/useGetRole.ts
  types/index.ts
  types/querys/ReserveMutationValues.ts
  types/querys/index.ts
  yarn.lock
Labels: ♻️ Refactor, ⚡️performance

#136 🔀 홈페이지 LCP 최적화
  components/HomePage/Section2/index.tsx
  components/HomePage/Section2/style.ts
  components/HomePage/Section3/style.ts
  styles/globals.css
Labels: ⚡️performance, 🎨 Publishing

#137 🔀 로그아웃 react-query로 변경
  components/Header/index.tsx
  hooks/index.ts
  hooks/useLogout.tsx
Labels: ⚡️performance

#138 🔀 Deploy
  components/Header/index.tsx
  components/HomePage/Section2/index.tsx
  components/HomePage/Section2/style.ts
  components/HomePage/Section3/style.ts
  hooks/index.ts
  hooks/useLogout.tsx
  styles/globals.css
Labels: 1️⃣ Priority: High, 🌏 Deploy

#139 🔀 공지사항 제목, 내용 최대길이 제한
  components/NoticePage/NoticeWritePage/index.tsx
Labels: 🐞 Bug, 🎨 Publishing

#140 🔀 홈페이지 이미지 import 및 style 수정
  components/HomePage/FunctionBox.tsx
  components/HomePage/Section2/style.ts
  hooks/useGetRole.tsx
Labels: 🎨 Publishing

#141 🔀 예약 테이블 가져오는 로직 수정
  apis/index.ts
  atoms/index.ts
  components/ReservationPage/index.tsx
  layout/index.tsx
  modals/PlaceSelect/index.tsx
  modals/ViewReservationModal/index.tsx
  modals/ViewReservationModal/style.ts
Labels: ⚡️performance

#142 🔀 color와 font를 emotion의 theme기능으로 정리
  layout/index.tsx
  pages/_app.tsx
  public/fonts/Pretendard-Black.woff
  public/fonts/Pretendard-ExtraBold.woff
  public/fonts/Pretendard-ExtraLight.woff
  public/fonts/Pretendard-Light.woff
  public/fonts/Pretendard-Thin.woff
  styles/theme.ts
Labels: ⚡️performance

#143 🔀 모달 디자인 변경사항 적용
  apis/queryKeyController.ts
  apis/urlController.ts
  assets/svg/CompltedImg.tsx
  components/commons/Modal/Container.ts
  modals/ConfirmReservationModal/index.tsx
  modals/LeaveReservationTableModal/index.tsx
  modals/RepresentativeMandateModal/index.tsx
  modals/StuStateModal/style.ts
  modals/UserRoleChangeModal/style.ts
  modals/ViewReservationModal/index.tsx
  modals/index.ts
Labels: 🎨 Publishing

#144 🔀 폰트, 색상 theme로 리팩토링
  assets/svg/InfoProfile.tsx
  assets/svg/UserProfile.tsx
  assets/svg/XMark.tsx
  assets/svg/index.ts
  components/Footer/style.ts
  components/Header/style.ts
  components/HomePage/FunctionBox.tsx
  components/HomePage/Section1/index.tsx
  components/HomePage/Section1/style.ts
  components/HomePage/Section2/style.ts
  components/HomePage/Section3/style.ts
  components/HomePage/Section4/style.ts
  components/MyPage/index.tsx
  components/MyPage/style.ts
  components/NoticePage/NoticeDetail/index.tsx
  components/NoticePage/NoticeDetail/style.ts
  components/NoticePage/NoticeItem/index.tsx
  components/NoticePage/NoticeItem/style.ts
  components/NoticePage/NoticeWritePage/index.tsx
  components/NoticePage/NoticeWritePage/style.ts
  components/NoticePage/Page/index.tsx
  components/NoticePage/Page/style.ts
  components/ReservationPage/ReservationTableItem/index.tsx
  components/ReservationPage/ReservationTableItem/style.ts
  components/ReservationPage/index.tsx
  components/ReservationPage/style.ts
  components/UserPage/UserItem/index.tsx
  components/UserPage/UserItem/style.ts
  components/UserPage/index.tsx
  components/UserPage/style.ts
  components/commons/Button/index.tsx
  components/commons/Button/style.ts
  components/commons/Input/index.tsx
  components/commons/Input/style.ts
  components/commons/Modal/Container.ts
  components/commons/Modal/Title.ts
  components/commons/Textarea/index.tsx
  components/commons/Textarea/style.ts
  modals/ConfirmReservationModal/index.tsx
  modals/PlaceSelect/style.ts
  modals/ReservationModal/Page/Completed/index.tsx
  modals/ReservationModal/Page/Completed/style.ts
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/MemberSelect/style.ts
  modals/ReservationModal/Page/Reason/index.tsx
  modals/StuStateModal/index.tsx
  modals/StuStateModal/style.ts
  modals/UserRoleChangeModal/index.tsx
  modals/UserRoleChangeModal/style.ts
  modals/ViewReservationModal/style.ts
  styles/theme.ts
  types/components/ButtonPropsType.ts
  types/components/InputPropsType.ts
  types/components/TextAreaPropsType.ts
Labels: ♻️ Refactor

#146 🔀 recoil state와 useState로 테이블 조회하는 로직 수정
  components/HomePage/Section1/index.tsx
  modals/PlaceSelect/index.tsx
  modals/PlaceSelect/style.ts
  modals/ReservationModal/Page/Reason/index.tsx
  modals/ViewReservationModal/index.tsx
Labels: ⚡️performance, 🎨 Publishing

#147 🔀 학생 정보 페이지 권한 받아오기 및 스타일 수정
  atoms/index.ts
  components/UserPage/UserItem/index.tsx
  components/UserPage/UserItem/style.ts
  components/UserPage/index.tsx
  components/UserPage/style.ts
  types/components/UserItemType.ts
Labels: ♻️ Refactor, 🎨 Publishing

#148 🔀 서버의 role 변경사항 적용
  atoms/index.ts
  components/UserPage/UserItem/index.tsx
  components/UserPage/index.tsx
  hooks/useGetRole.tsx
  pages/_app.tsx
  types/common/RoleTypes.ts
  types/common/index.ts
  types/components/GetRoleType.ts
  types/components/UserItemType.ts
  types/index.ts
  types/modals/ReservationData.ts
Labels: ⚡️performance

#149 🔀 헤더 반응형 수정
  components/Header/style.ts
Labels: 🎨 Publishing

#150 🔀 공지사항 추가, 수정한 후 처리 로직 수정
  components/NoticePage/NoticeItemList/index.tsx
  components/NoticePage/NoticeWritePage/index.tsx
  package.json
  yarn.lock
Labels: ⚡️performance, 🐞 Bug

#151 🔀 메인 페이지 반응형 스타일 수정
  assets/png/DescriptionImg1.png
  assets/png/DescriptionImg2.png
  components/HomePage/FunctionBox.tsx
  components/HomePage/Section1/style.ts
  components/HomePage/Section2/style.ts
  components/HomePage/Section3/index.tsx
  components/HomePage/Section3/style.ts
  components/HomePage/Section4/style.ts
Labels: 🎨 Publishing

#153 🔀 권한 변경 후 내 권한 다시 조회
  components/ReservationPage/ReservationTableItem/style.ts
  components/UserPage/UserItem/index.tsx
  modals/StudentStateModal/index.tsx
  modals/StudentStateModal/style.ts
  modals/UserRoleChangeModal/index.tsx
  modals/index.ts
  types/hooks/useGetRole.ts
Labels: 🐞 Bug

#154 🔀 테이블에 체크 상태 표시
  components/ReservationPage/ReservationTableItem/index.tsx
  styles/index.ts
Labels: 🎨 Publishing

#155 🔀 예약 최대 인원 적용
  components/HomePage/index.tsx
  components/ReservationPage/ReservationTableItem/index.tsx
  modals/ConfirmReservationModal/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/index.tsx
  types/components/ReservationModalProps.ts
  types/components/index.ts
Labels: ⚡️ Simple

#156 🔀 GAuth 로그인 로직 수정
  components/NoticePage/NoticeDetail/index.tsx
  components/NoticePage/NoticeDetail/style.ts
  hooks/index.ts
  hooks/usePostLogin.tsx
  layout/index.tsx
  libs/gauthLoginUri.ts
  libs/index.ts
  modals/DeleteTableCheckModal/index.tsx
  modals/LoginModal/index.tsx
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  yarn.lock
Labels: ⚡️performance, 🐞 Bug

#157 🔀 마이페이지 변경사항 반영 및 리팩토링
  components/MyPage/index.tsx
  components/MyPage/style.ts
  components/ReservationItem/index.tsx
  components/ReservationItem/style.ts
  types/components/MyPageType.ts
Labels: 1️⃣ Priority: High, ♻️ Refactor, 🎨 Publishing

#158 🔀 멤버 정보 검색 딜레이 줄이기
  components/NoticePage/NoticeItemList/index.tsx
  components/NoticePage/NoticeWritePage/index.tsx
  components/commons/Modal/Container.ts
  modals/ReservationModal/Page/MemberSelect/index.tsx
Labels: ⚡️performance

#159 🔀 층 별 홈베이스 테이블 위치 모달 띄우기
  assets/png/Floor2.png
  assets/png/Floor3.png
  assets/png/Floor4.png
  assets/png/index.ts
  components/ReservationItem/index.tsx
  components/ReservationPage/index.tsx
  components/ReservationPage/style.ts
  modals/FloorLocationModal/index.tsx
  modals/FloorLocationModal/style.ts
  modals/index.ts
Labels: ✨ Feature, 🎨 Publishing

#160 🔀 예약 조회 모달 로딩 ui 추가
  assets/svg/LoadingBook.tsx
  assets/svg/index.ts
  components/HomePage/FunctionBox.tsx
  components/Portal/index.tsx
  components/SEO/index.tsx
  components/commons/Button/index.tsx
  components/commons/Button/style.ts
  components/commons/Input/index.tsx
  components/commons/Input/style.ts
  components/commons/PageContainer/index.tsx
  components/commons/PageContainer/style.ts
  components/commons/Textarea/index.tsx
  components/commons/Textarea/style.ts
  modals/FloorLocationModal/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ViewReservationModal/LoadingComponent/index.tsx
  modals/ViewReservationModal/LoadingComponent/style.ts
  modals/ViewReservationModal/ViewReservationData/index.tsx
  modals/ViewReservationModal/ViewReservationData/style.ts
  modals/ViewReservationModal/index.tsx
  modals/ViewReservationModal/style.ts
  types/components/ButtonProps.ts
  types/components/FunctionBoxProps.ts
  types/components/InputProps.ts
  types/components/PageContainerProps.ts
  types/components/PortalProps.ts
  types/components/SeoProps.ts
  types/components/SeoPropsType.ts
  types/components/TextAreaProps.ts
  types/components/index.ts
  types/modals/ViewReservationDataProps.ts
  types/modals/ViewReservationDataResponseTypes.ts
  types/modals/index.ts
Labels: ⚡️performance, 🎨 Publishing

#161 🔀 GAuth 로그인 버튼 퍼블리싱
  assets/svg/GAuthLogo.tsx
  assets/svg/index.ts
  modals/LoginModal/index.tsx
  modals/LoginModal/style.ts
Labels: 🎨 Publishing

#162 🔀 헤더와 예약 페이지 반응형 적용
  components/Header/style.ts
  components/ReservationPage/index.tsx
  components/ReservationPage/style.ts
Labels: 🎨 Publishing

#164 🔀 홈베이스 테이블 예약 수정 조건 수정
  components/ReservationPage/ReservationTableItem/index.tsx
Labels: ⚡️ Simple, 🐞 Bug

#165 🔀 예약 오류들 수정
  components/ReservationPage/ReservationTableItem/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/Reason/index.tsx
  types/modals/ReservationData.ts
Labels: ⚡️performance, ✨ Feature

#167 🔀 날짜 state
  components/ReservationPage/index.tsx
Labels: ⚡️ Simple

#168 🔀 메인 페이지 제목 반응형
  components/HomePage/Section1/style.ts
  components/HomePage/Section2/style.ts
Labels: 2️⃣ Priority: Medium, 🎨 Publishing

#169 🔀 날짜 및 리다이렉트 수정
  apis/TokenManager.ts
  components/ReservationPage/index.tsx
  components/ReservationPage/style.ts
  modals/LoginModal/style.ts
Labels: ⚡️ Simple

#166 🔀 Deploy
  apis/TokenManager.ts
  components/HomePage/Section1/style.ts
  components/HomePage/Section2/style.ts
  components/ReservationPage/ReservationTableItem/index.tsx
  components/ReservationPage/index.tsx
  components/ReservationPage/style.ts
  modals/LoginModal/style.ts
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/Reason/index.tsx
  types/modals/ReservationData.ts
Labels: 🌏 Deploy

#170 🔀 예약 나가기 오류 해결
  modals/LeaveReservationTableModal/index.tsx
  modals/ViewReservationModal/index.tsx
Labels: ⚡️performance, 🐞 Bug

#172 🔀 예약 관련 이슈 해결
  apis/instance.ts
  components/ReservationPage/index.tsx
  components/commons/Input/style.ts
  modals/LeaveReservationTableModal/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/MemberSelect/style.ts
  modals/ReservationModal/Page/Reason/index.tsx
  modals/ViewReservationModal/index.tsx
  next.config.js
Labels: 1️⃣ Priority: High, 🐞 Bug

#171 🔀 공지글 등록 디바운스 처리
  components/NoticePage/NoticeWritePage/index.tsx
Labels: 1️⃣ Priority: High, 🐞 Bug

#173 🔀 내가 작성한 공지만 삭제, 수정 방식 변경
  components/NoticePage/NoticeDetail/index.tsx
  components/NoticePage/NoticeItem/index.tsx
  components/NoticePage/NoticeItemList/index.tsx
  types/components/NoticeItemType.ts
Labels: 1️⃣ Priority: High, 🐞 Bug

#174 🔀 공지 작성시 띄어쓰기를 제외한 공백 판별
  components/NoticePage/NoticeWritePage/index.tsx
Labels: 1️⃣ Priority: High, 🐞 Bug

#176 🔀 유저 권한 변경 이후 리스트 재요청
  components/UserPage/UserItem/index.tsx
  components/UserPage/index.tsx
  modals/UserRoleChangeModal/index.tsx
  types/components/UserItemType.ts
Labels: 3️⃣ Priority: Low, 🐞 Bug

#175 🔀 요청 횟수 줄이기
  pages/_app.tsx
Labels: ⚡️performance

#177 🔀 Deploy
  components/NoticePage/NoticeDetail/index.tsx
  components/NoticePage/NoticeItem/index.tsx
  components/NoticePage/NoticeItemList/index.tsx
  components/NoticePage/NoticeWritePage/index.tsx
  components/UserPage/UserItem/index.tsx
  components/UserPage/index.tsx
  modals/UserRoleChangeModal/index.tsx
  pages/_app.tsx
  types/components/NoticeItemType.ts
  types/components/UserItemType.ts
Labels: 🌏 Deploy

#179 🔀 학번 유무에 따른 표기 및 타입 변경
  components/MyPage/style.ts
  components/UserPage/UserItem/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/StudentStateModal/index.tsx
  types/components/UserItemType.ts
Labels: 🐞 Bug

#178 🔀 마이페이지 유저 이름, 예약 상태 스타일 수정
  components/MyPage/style.ts
Labels: 🎨 Publishing

#180 🔀 Deploy
  components/MyPage/style.ts
  components/UserPage/UserItem/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/StudentStateModal/index.tsx
  types/components/UserItemType.ts
Labels: 🌏 Deploy

#181 🔀 선생님일 때 예약 조회 버튼 보이기
  components/ReservationPage/ReservationTableItem/index.tsx
  modals/ViewReservationModal/index.tsx
Labels: 🐞 Bug

#182 🔀 예약 불가 시간 오류 핸들
  components/ReservationItem/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/MemberSelect/style.ts
  modals/ReservationModal/Page/Reason/index.tsx
  types/modals/ReasonProps.ts
  types/modals/index.ts
Labels: ✨ Feature, 🎨 Publishing

#183 🔀 공지 관련 response 변동에 따른 타입과 로직 변경
  components/NoticePage/NoticeDetail/index.tsx
  components/NoticePage/NoticeItem/index.tsx
  components/NoticePage/NoticeItemList/index.tsx
  components/NoticePage/NoticeWritePage/index.tsx
  pages/my-page.tsx
  pages/notice/[id].tsx
  pages/notice/index.tsx
  pages/reservation.tsx
  types/components/NoticeDetailType.ts
  types/components/NoticeItemListType.ts
  types/components/NoticeItemType.ts
  types/components/index.ts
Labels: 1️⃣ Priority: High, ♻️ Refactor

#184 🔀 Deploy
  components/NoticePage/NoticeDetail/index.tsx
  components/NoticePage/NoticeItem/index.tsx
  components/NoticePage/NoticeItemList/index.tsx
  components/NoticePage/NoticeWritePage/index.tsx
  pages/my-page.tsx
  pages/notice/[id].tsx
  pages/notice/index.tsx
  pages/reservation.tsx
  types/components/NoticeDetailType.ts
  types/components/NoticeItemListType.ts
  types/components/NoticeItemType.ts
  types/components/index.ts
Labels: 🌏 Deploy

#186 🔀 공지사항 상세 요청 조건
  components/NoticePage/NoticeDetail/index.tsx
Labels: 🐞 Bug

#185 🔀 변경 사항 develop에 반영
  components/ReservationItem/index.tsx
  components/ReservationPage/ReservationTableItem/index.tsx
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/MemberSelect/style.ts
  modals/ReservationModal/Page/Reason/index.tsx
  modals/ViewReservationModal/index.tsx
  types/modals/ReasonProps.ts
  types/modals/index.ts
Labels: 🌏 Deploy

#188 🔀 Deploy
  assets/png/Floor3.png
  components/NoticePage/NoticeDetail/index.tsx
Labels: 🌏 Deploy

#189 🔀 Google Analytics 적용
  libs/gtag.ts
  package.json
  pages/_app.tsx
  tsconfig.json
  yarn.lock
Labels: ✨ Feature

#190 🔀 Deploy
  libs/gtag.ts
  package.json
  pages/_app.tsx
  tsconfig.json
  yarn.lock
Labels: 🌏 Deploy

#191 🔀 공지 수정 버튼 권한 수정
  components/NoticePage/NoticeDetail/index.tsx
Labels: 🐞 Bug

#192 🔀 Deploy
  components/NoticePage/NoticeDetail/index.tsx
Labels: 🌏 Deploy

#193 🔀 파비콘 변경
  public/favicon.ico
Labels: ⚙ Setting, ⚡️ Simple

#194 🔀 Deploy
  public/favicon.ico
Labels: 🌏 Deploy

#195 🔀 accessToken null 해결
  apis/TokenManager.ts
  pages/_app.tsx
Labels: 🐞 Bug

#196 🔀 토큰 변질 오류 처리
  apis/TokenManager.ts
  apis/instance.ts
Labels: ⚡️performance, 🐞 Bug

#198 🔀 accessToken null 지운 거 되돌리기
  apis/instance.ts
Labels: 🐞 Bug

#197 🔀 Deploy
  apis/TokenManager.ts
  apis/instance.ts
Labels: 🌏 Deploy

#199 🔀 예약 멤버 선택 모달 이미지 크기 수정
  modals/ReservationModal/Page/MemberSelect/index.tsx
  modals/ReservationModal/Page/MemberSelect/style.ts
Labels: 🎨 Publishing

#200 🔀 마이페이지 예약 내역이 없을 경우 안내 메시지 띄우기
  apis/instance.ts
  components/MyPage/index.tsx
  components/MyPage/style.ts
Labels: 🎨 Publishing

#201 🔀 Deploy
  apis/instance.ts
  components/MyPage/index.tsx
  components/MyPage/style.ts
Labels: 🌏 Deploy

#202 🔀 공지사항 상세 id undefined 요청 해결
  components/NoticePage/NoticeDetail/index.tsx
Labels: 🐞 Bug

#203 🔀 예약 사유 스타일 수정
  modals/ViewReservationModal/ViewReservationData/index.tsx
  modals/ViewReservationModal/ViewReservationData/style.ts
  modals/ViewReservationModal/index.tsx
Labels: 🎨 Publishing

#204 🔀 예약 멤버 이름 줄바꿈 스타일 수정
  components/ReservationPage/ReservationTableItem/style.ts
Labels: 🎨 Publishing

#205 🔀 tanstack query에서 오류를 잡지 못 하는 오류 해결
  apis/instance.ts
  modals/LeaveReservationTableModal/index.tsx
Labels: 1️⃣ Priority: High, 🐞 Bug

#207 🔀 예약 연속 요청 제한하기
  modals/ReservationModal/Page/Reason/index.tsx
Labels: ⚡️performance

#208 🔀 홈베이스 상세 조회의 경우 변경
  modals/PlaceSelect/index.tsx
Labels: ⚡️performance

#206 🔀 Deploy
  apis/instance.ts
  components/NoticePage/NoticeDetail/index.tsx
  components/ReservationPage/ReservationTableItem/style.ts
  modals/LeaveReservationTableModal/index.tsx
  modals/PlaceSelect/index.tsx
  modals/ReservationModal/Page/Reason/index.tsx
  modals/ViewReservationModal/ViewReservationData/index.tsx
  modals/ViewReservationModal/ViewReservationData/style.ts
  modals/ViewReservationModal/index.tsx
Labels: 🌏 Deploy

#209 🔀 4층 테이블 이미지 교체
  apis/instance.ts
  assets/png/Floor4.png
Labels: ⚡️ Simple

#210 🔀 Deploy
  apis/instance.ts
  assets/png/Floor4.png
Labels: 🌏 Deploy

#211 🔀 멤버 검색 쓰로틀링에서 디바운싱으로 변경
  modals/ReservationModal/Page/MemberSelect/index.tsx
Labels: ⚡️performance
